/*
* kornapp.h -- Declaration of class KornApp.
* Generated by newclass on Sun Apr 22 23:50:49 EST 2001.
*/
#ifndef SSK_KORNAPP_H
#define SSK_KORNAPP_H

#include<kuniqueapp.h>

class KornShell;

/**
* @short KornApp
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id: kornapp.h 93752 2001-04-24 14:36:11Z taj $
*/
class KornApp : public KUniqueApplication
{
	Q_OBJECT

public:
	/**
	* KornApp Constructor
	*/
	KornApp() : KUniqueApplication(), _shell( 0 ), _instanceCount( 0 ) {}

	/**
	* KornApp Destructor
	*/
	virtual ~KornApp(){}

	virtual int newInstance();
	void setShell( KornShell *shell ){ _shell = shell; };
	
private:
	KornShell *_shell;
	int _instanceCount;

	KornApp& operator=( const KornApp& );
	KornApp( const KornApp& );
};

#endif // SSK_KORNAPP_H
