/**********************************************************************

	--- Qt Architect generated file ---

	File: defaultfiltersdata.cpp
	Last generated: Tue Jul 28 02:30:57 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "defaultfiltersdata.h"
#include "../config.h"

#undef Inherited
#define Inherited QFrame

#include <qlabel.h>
#include <qbuttongroup.h>
#include <qlayout.h>

#include <klocale.h>

defaultfiltersdata::defaultfiltersdata
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
        QBoxLayout *lay = new QVBoxLayout (this, 10);
	lay->addSpacing (10);

	QButtonGroup* bg1;
	bg1 = new 
	  QButtonGroup( i18n("Allow External Colors"), 
			this, "ButtonGroup_1" );
	lay->addWidget( bg1 );

	QBoxLayout *bl= new QVBoxLayout (bg1, 10);
	bl->addSpacing(10);

	kSircColours = new 
	  QCheckBox( i18n("Allow &kSirc Color codes"), bg1 , "CheckBox_1" );
	kSircColours->setAutoRepeat( FALSE );
	kSircColours->setChecked( TRUE );
	bl->addWidget(kSircColours);

	mircColours = new 
	  QCheckBox( i18n("Allow &mirc Color codes"), bg1, "CheckBox_2" );
	mircColours->setAutoRepeat( FALSE );
	mircColours->setChecked( TRUE );
	bl->addWidget(mircColours);

	QButtonGroup* bg2;
	bg2 = new 
	  QButtonGroup( i18n("Color Nicks in Channels"), 
			this, "ButtonGroup_2" );
	lay->addWidget( bg2 );
	QGridLayout *gl = new QGridLayout ( bg2, 6, 5, 10);
	gl->addRowSpacing(0, 10);
	gl->addRowSpacing(5, 10);

	QLabel* l = new 
	  QLabel( i18n("Foreground"), bg2, "Label_5" );
	gl->addMultiCellWidget(l, 1, 2, 0, 0);

	NickFColour = new QComboBox( FALSE, bg2, "ComboBox_2" );
	NickFColour->setSizeLimit( 17 );
	gl->addMultiCellWidget(NickFColour, 1, 2, 1, 1);

	LabelNickB = new 
	  QLabel( i18n("Background"), bg2, "Label_3" );
	gl->addMultiCellWidget(LabelNickB, 3, 4, 0, 0);

	NickBColour = new QComboBox( FALSE, bg2, "ComboBox_3" );
	NickBColour->setSizeLimit( 17 );
	gl->addMultiCellWidget(NickBColour, 3, 4, 1, 1);
	
	SLE_SampleColourNick = new 
	  QLineEdit( i18n("Sample"), bg2, "LineEdit_1" );
	SLE_SampleColourNick->setEchoMode( QLineEdit::Normal );
	SLE_SampleColourNick->setFrame( TRUE );
	gl->addMultiCellWidget(SLE_SampleColourNick, 2, 3, 3, 3);
	
	
	QButtonGroup* bg4;
	bg4 = new 
	  QButtonGroup( i18n("Highlight Your Nick"), this, "ButtonGroup_4" );
	lay->addWidget( bg4 );
	
	gl = new QGridLayout(bg4, 5, 5, 10);
	gl->addRowSpacing(0, 10);

	
	l = new QLabel( i18n("Color"), bg4, "Label_6" );
	gl->addWidget(l, 2, 0);

	usHighlightColour = new 
	  QComboBox( FALSE, bg4, "ComboBox_1" );
	usHighlightColour->setSizeLimit( 17 );
	gl->addWidget( usHighlightColour, 2, 1);

	SLE_SampleHighlight = new 
	  QLineEdit( i18n("Sample"), bg4, "LineEdit_2" );
	SLE_SampleHighlight->setEchoMode( QLineEdit::Normal );
	SLE_SampleHighlight->setFrame( TRUE );
	gl->addMultiCellWidget(SLE_SampleHighlight, 1, 3, 3, 3 );
}


defaultfiltersdata::~defaultfiltersdata()
{
}
#include "defaultfiltersdata.moc"
