/**********************************************************************

	--- Qt Architect generated file ---

	File: startupdata.cpp
	Last generated: Sat Jan 17 19:44:50 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "startupdata.h"
#include "../config.h"

#undef Inherited
#define Inherited QWidget

#include <qlabel.h>
#include <qbuttongroup.h>
#include <qpushbutton.h>
#include <qlayout.h>

#include <klocale.h>

startupdata::startupdata
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
        QGridLayout *lay = new QGridLayout (this, 1, 1, 10);

	QLabel* l = new QLabel( i18n( "Nick" ), this, "Label_1" );
	lay->addWidget(l, 0, 0);

	SLE_Nick = new QLineEdit( "", this, "LineEdit_1" );
	SLE_Nick->setEchoMode( QLineEdit::Normal );
	SLE_Nick->setFrame( TRUE );
	lay->addWidget(SLE_Nick, 0, 1);


	l = new QLabel( i18n("Real Name"), this, "Label_2" );
	lay->addWidget(l, 1, 0);

	SLE_RealName = new QLineEdit( "", this, "LineEdit_2" );
	SLE_RealName->setEchoMode( QLineEdit::Normal );
	SLE_RealName->setFrame( TRUE );
	lay->addWidget(SLE_RealName, 1, 1);
	
	QButtonGroup* bg = new 
	  QButtonGroup( i18n( "Notify List" ), this, "ButtonGroup_1" );
	lay->addMultiCellWidget(bg, 2, 2, 0, 1);
	
	QGridLayout *gl =  new QGridLayout(bg, 1, 1, 10);
	gl->addRowSpacing(0, 5);

	LB_Nicks = new QListBox( bg, "ListBox_1" );
	LB_Nicks->setMultiSelection( FALSE );
	gl->addMultiCellWidget (LB_Nicks, 1, 5, 0, 0);
	
	QPushButton* pb = new 
	  QPushButton( i18n( "&Delete" ), bg, "PushButton_1" );
	connect( pb, SIGNAL(clicked()), SLOT(nicks_delete()) );
	pb->setAutoRepeat( FALSE );
	gl->addWidget(pb, 1, 1);

	SLE_Nicks = new 
	  QLineEdit( "", bg, "LineEdit_3" );
	connect( SLE_Nicks, SIGNAL(textChanged(const QString &)), 
		 SLOT(sle_add_update(const QString &)) );
	SLE_Nicks->setEchoMode( QLineEdit::Normal );
	SLE_Nicks->setFrame( TRUE );
	gl->addWidget(SLE_Nicks, 3, 1);

	B_AddNicks = new 
	  QPushButton( i18n( "&Add" ), bg, "PushButton_2" );
	connect( B_AddNicks, SIGNAL(clicked()), SLOT(nicks_add()) );
	B_AddNicks->setAutoRepeat( FALSE );
	gl->addWidget(B_AddNicks, 5, 1);
}


startupdata::~startupdata()
{
}
void startupdata::nicks_delete()
{
}
void startupdata::nicks_add()
{
}
void startupdata::sle_add_update(const QString &)
{
}
#include "startupdata.moc"
